lbyledu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lbyledu.admin import admin_site
from article.views import IndexView


urlpatterns = [
    path('admin/', admin_site.urls),
    path('', IndexView.as_view(), name="index"),
    path('', include('organization.urls', namespace="organization")),
    path('', include('article.urls', namespace="article")),
    path('', include('users.urls', namespace="users")),
    path('office/', include('office.urls', namespace="office")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office/urls.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-23 14:43:39
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-23 14:43:39
@Description:
"""
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import OfficeView, DocumentDetailView, DocumentAllListView, DocumentNotSignedListView, DocumentPublishView
from .views import ArticleManageListView, ArticleManageAllListView, ArticlePublishView, ArticleDeleteView, ArticleUpdateView
from .views import UserManageView
from .views import AddressBookView

app_name = 'office'
urlpatterns = [
    path('', login_required()(OfficeView.as_view()), name="index"),
    path('document/', login_required()(DocumentNotSignedListView.as_view()), name="document"),
    path('document/all/', login_required()(DocumentAllListView.as_view()), name="document_all"),
    path('document/publish/', login_required()(DocumentPublishView.as_view()), name="document_publish"),
    path('document/<int:number>', login_required()(DocumentDetailView.as_view()), name="document_detail"),
    path('article/', login_required()(ArticleManageListView.as_view()), name="article"),
    path('article/all/', login_required()(ArticleManageAllListView.as_view()), name="article_all"),
    path('article/publish/', login_required()(ArticlePublishView.as_view()), name="article_publish"),
    path('article/update/<int:article_id>', login_required()(ArticleUpdateView.as_view()), name="article_update"),
    path('article/delete/<int:article_id>', login_required()(ArticleDeleteView.as_view()), name="article_delete"),
    path('user/', login_required()(UserManageView.as_view()), name="user"),
    path('addressbook/', login_required()(AddressBookView.as_view()), name="address_book"),
]

users/urls.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-21 16:00:03
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-21 16:00:03
@Description:
"""
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import LoginView, RegisterView, LogoutView, PasswordChangeView, UserProfileView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login", kwargs={'authentication_form': LoginForm}),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', login_required()(LogoutView.as_view()), name="logout"),
    path('passwordchange/', login_required()(PasswordChangeView.as_view()), name="password_change"),
    path('user/<username>/', login_required()(UserProfileView.as_view()), name="user_profile"),
    path('user/password/reset/', PasswordResetView.as_view(), name="password_reset"),
    path('user/password/reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('user/password/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('user/reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

office/models.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-23 15:15:01
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-23 15:15:01
@Description:
"""
import logging
from abc import abstractmethod

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.functional import cached_property
from django.utils.timezone import now
from ckeditor_uploader.fields import RichTextUploadingField

from lbyledu.utils import cache_decorator, cache
from users.models import UserGroup, UserProfile
from organization.models import Organization

logger = logging.getLogger(__name__)

# Create your models here.
class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField(default=now, verbose_name="创建时间")
    last_mod_time = models.DateTimeField(default=now, verbose_name="修改时间")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Document(BaseModel):
    title = models.CharField(max_length=200, verbose_name="标题")
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="发布人")
    content = RichTextUploadingField(verbose_name="正文")
    receiver = models.ManyToManyField(UserProfile, blank=True, related_name="documents", verbose_name="收件人")
    receiver_group = models.ForeignKey(UserGroup, on_delete=models.CASCADE, verbose_name="收件用户组")
    checked_receiver = models.ManyToManyField(UserProfile, blank=True, related_name="checked_documents", verbose_name="已签收的用户")
    number = models.IntegerField(unique=True, verbose_name="编号")

    class Meta:
        verbose_name = "公文"
        verbose_name_plural = verbose_name
        ordering = ['-created_time']
        get_latest_by = 'id'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("office:document_detail", kwargs={"number": self.number})


class OrganizationAdmins(BaseModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name="单位")
    admin  = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="管理员")

    class Meta:
        verbose_name = "网站管理员"
        verbose_name_plural = verbose_name

organization/models.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-08 15:27:21
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-08 15:27:21
@Description:
"""
import logging
from abc import abstractmethod

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils.functional import cached_property
from django.utils.timezone import now
from django.urls import reverse
from lbyledu.utils import cache_decorator, cache

logger = logging.getLogger(__name__)


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField(default=now, verbose_name="创建时间")
    last_mod_time = models.DateTimeField(default=now, verbose_name="修改时间")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Organization(BaseModel):
    CATEGORY_CHOICES = (
        ('center', '中心学校'),
        ('middle', '中学'),
        ('primary', '小学'),
        ('kindergarten', '幼儿园')
    )
    name = models.CharField(max_length=50, verbose_name="单位名称")
    category = models.CharField(choices=CATEGORY_CHOICES, default='center', max_length=12, verbose_name="分类")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    address = models.CharField(max_length=150, verbose_name="地址")
    website = models.CharField(max_length=100, null=True, blank=True, verbose_name="网址")
    telephone = models.CharField(max_length=20, verbose_name="联系电话")
    desc = RichTextUploadingField(verbose_name="概况")

    class Meta:
        verbose_name = "单位信息"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organization:org_detail', kwargs={
            'org_category': self.category,
            'org_id': self.id
        })

    def viewed(self):
        self.veiws += 1
        self.save(update_fields=['views'])


class Leader(BaseModel):
    GENDER_CHOICES = (
        ("male", "男"),
        ("female", "女")
    )
    name = models.CharField(max_length=20, verbose_name="姓名")
    gender = models.CharField(choices=GENDER_CHOICES, default="male", max_length=6, verbose_name="性别")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    birthday = models.DateField(verbose_name="生日", null=True, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name="单位")
    mobile = models.CharField(max_length=11, null=True, blank=True, verbose_name="联系电话")
    desc = RichTextUploadingField(verbose_name="简介")

    class Meta:
        verbose_name = "领导介绍"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def viewed(self):
        self.veiws += 1
        self.save(update_fields=['views'])

users/models.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-08 15:51:37
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-08 15:51:37
@Description:
"""
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.urls import reverse
from django.utils.timezone import now

from organization.models import Organization


class UserProfile(AbstractUser):
    POSITION_CHOICES = (
        ("zxxxz", "中心校校长"),
        ("zxxz", "中学校长"),
        ("xxxz", "小学校长"),
        ("teacher", "教师")
    )
    GENDER_CHOICES = (
        ("male", "男"),
        ("female", "女")
    )
    realname = models.CharField(max_length=50, verbose_name="真实姓名", default="")
    level = models.CharField(max_length=50, verbose_name="级别", default="")
    birthday = models.DateField(verbose_name="生日", null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, default="male", max_length=6, verbose_name="性别")
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name="单位")
    position = models.CharField(choices=POSITION_CHOICES, default="teacher", max_length=7, verbose_name="职务")
    mobile = models.CharField(max_length=11, null=True, blank=True, verbose_name="电话")
    create_time = models.DateTimeField(default=now, verbose_name="创建时间")
    last_mod_time = models.DateTimeField(default=now, verbose_name="修改时间")
    is_active = models.BooleanField(default=False, verbose_name="是否激活")
    first_name = None
    last_name = None

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:user_profile', kwargs={'username': self.username})


class UserGroup(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField(default=now, verbose_name="创建时间")
    last_mod_time = models.DateTimeField(default=now, verbose_name="修改时间")
    name = models.CharField(max_length=100, verbose_name="用户组名称", default="")
    users = models.ManyToManyField(UserProfile, related_name='usergroups', verbose_name="用户")

    class Meta:
        verbose_name = "用户组"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class EmailVerifyRecord(models.Model):
    SEND_TYPE_CHOICES = (
        ("register", "注册"),
        ("forget", "找回密码")
    )
    code = models.CharField(max_length=20, verbose_name="验证码")
    email = models.EmailField(max_length=50, verbose_name="邮箱")
    send_type = models.CharField(choices=SEND_TYPE_CHOICES, max_length=8, verbose_name="验证码类型")
    send_time = models.DateTimeField(default=now, verbose_name="发送时间")

    class Meta:
        verbose_name = "邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)

office/forms.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-26 13:34:46
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-26 13:34:46
@Description:
"""
from django import forms
from django.forms import widgets
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from users.models import UserGroup
from article.models import Article


class DocumentPublishForm(forms.Form):
    DEFAULT_ERROR_MESSAGES = {'required': '请填写该字段', 'invalid_choice': '请正确填写该字段'}
    receiver_group = forms.ChoiceField(required=True, error_messages={'required': '请选择接收用户组', 'invalid_choice': '请选择接收用户组'}, widget=widgets.Select(attrs={"class": "form-control"}))
    title = forms.CharField(required=True, error_messages = DEFAULT_ERROR_MESSAGES)
    number = forms.IntegerField(required=True, error_messages = DEFAULT_ERROR_MESSAGES)
    author = forms.CharField(required=True, error_messages = DEFAULT_ERROR_MESSAGES)
    content = forms.CharField(required=True, error_messages = DEFAULT_ERROR_MESSAGES)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DocumentPublishForm, self).__init__(*args, **kwargs)

        self.fields['receiver_group'].choices = self.get_receiver_group()

        self.fields['title'].widget = widgets.TextInput(attrs={"class": "form-control"})
        self.fields['number'].widget = widgets.NumberInput(attrs={"class": "form-control"})
        self.fields['author'].widget = widgets.TextInput(attrs={"readonly": True, "value": self.user.realname, "class": "form-control"})
        self.fields['content'].widget = CKEditorUploadingWidget()

        self.fields['receiver_group'].label = "接收用户组"
        self.fields['title'].label = "公文标题"
        self.fields['number'].label = "公文编号"
        self.fields['author'].label = "发布人"
        self.fields['content'].label = ""
        
    def get_receiver_group(self):
        receiver_group = (('-1', '请选择接收用户组'),)
        for group in UserGroup.objects.all():
            group_tup = ((str(group.id), group.name),)
            receiver_group += group_tup

        return receiver_group

    def is_valid(self):
        valid = super(DocumentPublishForm, self).is_valid()

        if not valid:
            return valid

        if self.cleaned_data['receiver_group'] == '-1':
            self._errors['no_receiver_group'] = '* 请选择一个接收用户组'
            return False

        return True


class ArticlePublishForm(forms.ModelForm):
    DEFAULT_ERROR_MESSAGES = {'required': '请填写该字段', 'invalid_choice': '请正确填写该字段'}
    
    class Meta:
        model = Article
        fields = ['title', 'category', 'author', 'origin', 'content', 'has_check', 'is_banner']
        widgets = {
            'title': widgets.TextInput(attrs={"class": "form-control"}),
            'category': widgets.Select(attrs={"class": "form-control"}),
            'author': widgets.TextInput(attrs={"class": "form-control"}),
            'origin': widgets.Select(attrs={"class": "form-control"}),
            'content': CKEditorUploadingWidget(),
        }
        labels = {
            'title': "文章标题",
            'category': "文章板块",
            'author': "作者",
            'origin': "单位",
            'content': "",
            'has_check': "是否通过审核",
            'is_banner': "是否用于首页轮播图"
        }
        error_messages = {
            'title': {
                'max_length': "文章题目过长。",
            }, 
        }

templates/office/article_list.html
{% extends "office/office_base.html" %}
{% load static %}

{% block main %}
<div class="main-list-body panel-body">
    <div class="content-card office-tags article-manage">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="{% url 'office:article' %}" class="nav-link{% if "/all/" not in request.path and "/publish/" not in request.path %} active{% endif %}">未审批文章</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'office:article_all' %}" class="nav-link{% if "/all/" in request.path %} active{% endif %}">全部文章</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'office:article_publish' %}" class="nav-link{% if "/publish/" in request.path %} active{% endif %}">发表文章</a>
            </li>
        </ul>
        <ul class="list-group">
        {% for article in article_list %}
            <li class="list-group-item"><a href="{{ article.get_absolute_url }}">
                    <span class="list-group-item-title">{{ article.title }}</span>
                    <span class="list-group-item-date">{{ article.pub_date | date:"Y-m-d" }}</span>
                </a>
            <div class="text-edit-block">
                <form action="{% url 'office:article_update' article.id %}" method="GET">
                    <button type="submit" class="btn-update text-primary">编辑</button>
                </form>
                <form action="{% url 'office:article_delete' article.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn-delete text-danger">删除</button>
                </form>
            </div></li>
        {% empty %}
        <li class="list-group-item">暂无文章</li>
        {% endfor %}
        </ul>
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="main-pagination">
            <ul class="pagination pagination-sm justify-content-end">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">首页</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">首页</a></li>
                <li class="page-item disabled"><a class="page-link" href="">上一页</a></li>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
                {% endif %}
                {% for i in left %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}
            {% endif %}
                <li class="page-item"><a class="page-link" href="?page={{  page_obj.number  }}">{{ page_obj.number }}</a></li>
            {% if right %}
                {% for i in right %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}
                {% if right_has_more %}
                    <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
                {% endif %}
            {% endif %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">下一页</a></li>
                <li class="page-item disabled"><a class="page-link" href="">尾页</a></li>
            {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock main %}

templates/office/article_publish.html
{% extends "office/office_base.html" %}
{% load static %}
{% load article_tags %}

{% block main %}
<div class="main-list-body panel-body">
    <div class="content-card office-tags">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="{% url 'office:article' %}" class="nav-link">未审批文章</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'office:article_all' %}" class="nav-link">全部文章</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'office:article_publish' %}" class="nav-link active">发表文章</a>
            </li>
        </ul>
        {% if '/article/update/' in request.path %}
        <form action="{{ article.get_update_url }}" method="POST">
        {% else %}
        <form action="{% url 'office:article_publish' %}" method="POST">
        {% endif %}
            <div class="form-row">
                {% csrf_token %}
                {{ form.none_field_errors }}
                {{ form.media }}
                {% for field in form %}
                <div class="form-group col-7">
                    {% if field.label %}
                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                    {% endif %}
                    {{ field }}
                    {% if field.errors %}
                    <div class="invalid-feedback">
                        {{ field.errors.as_text }}
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn publish-btn btn-primary">发布</button>
        </form>
    </div>
</div>
{% endblock main %}

templates/office/document_all.html
{% extends "office/office_base.html" %}
{% load static %}
{% load article_tags %}

{% block main %}
<div class="content-card office-tags">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a href="{% url 'office:document' %}" class="nav-link">未签收公文</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'office:document_all' %}" class="nav-link active">全部公文</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'office:document_publish' %}" class="nav-link">发布公文</a>
        </li>
    </ul>
    <ul class="list-group">
    {% for document in document_list %}
        <li class="list-group-item"><a href="javascript:void(0)">
                <span class="list-group-item-title">{{ document.title }}</span>
                <span class="list-group-item-date">{{ document.created_time | date:"Y-m-d" }}</span>
            </a></li>
    {% endfor %}
    </ul>
    {% if is_paginated %}
    <nav aria-label="Page navigation example" class="main-pagination">
        <ul class="pagination pagination-sm justify-content-end">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">首页</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="">首页</a></li>
            <li class="page-item disabled"><a class="page-link" href="">上一页</a></li>
        {% endif %}
        {% if left %}
            {% if left_has_more %}
                <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
            {% endif %}
            {% for i in left %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
        {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{  page_obj.number  }}">{{ page_obj.number }}</a></li>
        {% if right %}
            {% for i in right %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if right_has_more %}
                <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
            {% endif %}
        {% endif %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="">下一页</a></li>
            <li class="page-item disabled"><a class="page-link" href="">尾页</a></li>
        {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock main %}

templates/office/document_notsigned.html
{% extends "office/office_base.html" %}
{% load static %}
{% load article_tags %}

{% block main %}
<div class="content-card office-tags">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a href="{% url 'office:document' %}" class="nav-link active">未签收公文</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'office:document_all' %}" class="nav-link">全部公文</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'office:document_publish' %}" class="nav-link">发布公文</a>
        </li>
    </ul>
    <ul class="list-group">
    {% for document in document_list %}
        <li class="list-group-item"><a href="javascript:void(0)">
                <span class="list-group-item-title">{{ document.title }}</span>
                <span class="list-group-item-date">{{ document.created_time | date:"Y-m-d" }}</span>
            </a></li>
    {% endfor %}
    </ul>
    {% if is_paginated %}
    <nav aria-label="Page navigation example" class="main-pagination">
        <ul class="pagination pagination-sm justify-content-end">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">首页</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="">首页</a></li>
            <li class="page-item disabled"><a class="page-link" href="">上一页</a></li>
        {% endif %}
        {% if left %}
            {% if left_has_more %}
                <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
            {% endif %}
            {% for i in left %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
        {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{  page_obj.number  }}">{{ page_obj.number }}</a></li>
        {% if right %}
            {% for i in right %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if right_has_more %}
                <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
            {% endif %}
        {% endif %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="">下一页</a></li>
            <li class="page-item disabled"><a class="page-link" href="">尾页</a></li>
        {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock main %}

templates/office/office_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>网上办公 - 豫灵镇中心学校</title>

    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/office.css' %}" rel="stylesheet">
    {% block css %}{% endblock css %}
</head>

<body>

    {% include "header.html" %}

    {% include "toolbar.html" %}

    <div class="main-content container">
        <div class="row row-offcanvas row-offcanvas-left">
            <div class="main-content container">
                <div class="row row-offcanvas row-offcanvas-left">
                    <div class="col-sm-4 col-md-3 sidebar-offcanvas main-content-sidebar" id="sidebar">
                        <ul class="sidebar-list-group">
                            <li><a href="javascript:void(0)" class="sidebar-list-item top">网上办公</a></li>
                            <li><a href="{% url 'office:index' %}" class="sidebar-list-item{% ifequal current_route '' %} active{% endifequal %}">网上办公首页</a></li>
                            <li><a href="{% url 'office:document' %}" class="sidebar-list-item{% ifequal current_route 'document' %} active{% endifequal %}">公文签收</a></li>
                            <li><a href="{% url 'office:article' %}" class="sidebar-list-item{% ifequal current_route 'article' %} active{% endifequal %}">文章管理</a></li>
                            <li><a href="{% url 'office:user' %}" class="sidebar-list-item{% ifequal current_route 'user' %} active{% endifequal %}">审核新用户</a></li>
                            <li><a href="javascript:void(0)" class="sidebar-list-item{% ifequal current_route 'addressbook' %} active{% endifequal %}">通讯录</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-8 col-md-9 main-content-body">
                        <div class="panel">
                            {% block main %}
                            
                            {% endblock main %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "footer.html" %}

    <!-- JavaScript -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block js %}{% endblock js %}
</body>

</html>