article/urls.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-08 14:55:32
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-08 14:55:32
@Description:
"""
from django.urls import path, include
from .views import ArticleListView, ArticleDetailView, DevelopView

app_name = 'article'
urlpatterns = [
    path('developing/', DevelopView.as_view(), name="developing"),
    path('category/<int:parent_id>/<int:child_id>', ArticleListView.as_view(), name="category_detail"),
    path('article/<int:year>/<int:month>/<int:day>/<int:article_id>', ArticleDetailView.as_view(), name="detail_by_id")
]

lbyledu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lbyledu.admin import admin_site
from article.views import IndexView


urlpatterns = [
    path('admin/', admin_site.urls),
    path('', IndexView.as_view(), name="index"),
    path('', include('organization.urls', namespace="organization")),
    path('', include('article.urls', namespace="article")),
    path('', include('users.urls', namespace="users")),
    path('office/', include('office.urls', namespace="office")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office/urls.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-23 14:43:39
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-23 14:43:39
@Description:
"""
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import OfficeView, DocumentDetailView, DocumentAllListView, DocumentNotSignedListView, DocumentPublishView
from .views import ArticleManageListView, ArticleManageAllListView, ArticlePublishView, ArticleDeleteView, ArticleUpdateView
from .views import UserManageView
from .views import AddressBookView

app_name = 'office'
urlpatterns = [
    path('', login_required()(OfficeView.as_view()), name="index"),
    path('document/', login_required()(DocumentNotSignedListView.as_view()), name="document"),
    path('document/all/', login_required()(DocumentAllListView.as_view()), name="document_all"),
    path('document/publish/', login_required()(DocumentPublishView.as_view()), name="document_publish"),
    path('document/<int:number>', login_required()(DocumentDetailView.as_view()), name="document_detail"),
    path('article/', login_required()(ArticleManageListView.as_view()), name="article"),
    path('article/all/', login_required()(ArticleManageAllListView.as_view()), name="article_all"),
    path('article/publish/', login_required()(ArticlePublishView.as_view()), name="article_publish"),
    path('article/update/<int:article_id>', login_required()(ArticleUpdateView.as_view()), name="article_update"),
    path('article/delete/<int:article_id>', login_required()(ArticleDeleteView.as_view()), name="article_delete"),
    path('user/', login_required()(UserManageView.as_view()), name="user"),
    path('addressbook/', login_required()(AddressBookView.as_view()), name="address_book"),
]

users/urls.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-21 16:00:03
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-21 16:00:03
@Description:
"""
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import LoginView, RegisterView, LogoutView, PasswordChangeView, UserProfileView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login", kwargs={'authentication_form': LoginForm}),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', login_required()(LogoutView.as_view()), name="logout"),
    path('passwordchange/', login_required()(PasswordChangeView.as_view()), name="password_change"),
    path('user/<username>/', login_required()(UserProfileView.as_view()), name="user_profile"),
    path('user/password/reset/', PasswordResetView.as_view(), name="password_reset"),
    path('user/password/reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('user/password/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('user/reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

article/models.py
#!/usr/bin/env python


"""
@Author: gorywong
@Date: 2019-01-08 12:35:51
@Software: Visual Studio Code
@Last Modified by: gorywong
@Last Modified time: 2019-01-08 12:35:51
@Description:
"""
import logging
from abc import abstractmethod

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.functional import cached_property
from django.utils.timezone import now
from ckeditor_uploader.fields import RichTextUploadingField

from lbyledu.utils import cache_decorator, cache
from organization.models import Organization

logger = logging.getLogger(__name__)


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField(default=now, verbose_name="创建时间")
    last_mod_time = models.DateTimeField(default=now, verbose_name="修改时间")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Index(BaseModel):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="板块名")
    weight = models.PositiveIntegerField(unique=True, verbose_name="序号(数字越小越靠前)")

    class Meta:
        verbose_name = "首页板块"
        verbose_name_plural = verbose_name
        ordering = ['weight']
        get_latest_by = 'id'

    def __str__(self):
        return self.category.name


class Article(BaseModel):
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表')
    )
    title = models.CharField(max_length=200, unique=True, verbose_name="标题")
    category = models.ForeignKey('Category', on_delete=models.CASCADE, limit_choices_to={'parent_category__isnull': False}, verbose_name="分类")
    author = models.CharField(max_length=50, verbose_name="作者")
    origin = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name="单位")
    content = RichTextUploadingField(verbose_name="正文")
    pub_date = models.DateTimeField(default=now, verbose_name="发布时间")
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, default='p', verbose_name="文章状态")
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")
    has_check = models.BooleanField(default=False, verbose_name="是否通过审核")
    is_banner = models.BooleanField(default=False, verbose_name="是否用于首页轮播图")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ['-pub_date']
        get_latest_by = 'id'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:detail_by_id', kwargs={
            'article_id': self.id,
            'year': self.created_time.year,
            'month': self.created_time.month,
            'day': self.created_time.day
        })

    def get_update_url(self):
        return reverse('office:article_update', kwargs={'article_id': self.id})

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_admin_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.pk))

    def next_article(self):
        return Article.objects.filter(pub_date__lt=self.pub_date, category=self.category, status='p', has_check=True).order_by('-pub_date').first()

    def prev_article(self):
        return Article.objects.filter(pub_date__gt=self.pub_date, category=self.category, status='p', has_check=True).order_by('pub_date').first()


class Category(BaseModel):
    name = models.CharField(max_length=30, unique=True, verbose_name="分类名")
    parent_category = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, limit_choices_to={'parent_category__isnull': True}, related_name='+', verbose_name="父级分类")
    default_child_category = models.ForeignKey('self', blank=True, null=True, limit_choices_to={'parent_category__isnull': False}, related_name='+', on_delete=models.CASCADE, verbose_name="默认子类")

    class Meta:
        ordering = ['id']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        if self.parent_category:
            return self.parent_category.name + '-->' + self.name
        else:
            return self.name

    def get_absolute_url(self):
        if self.parent_category:
            parent_id = self.parent_category.id
            child_id = self.id
        else:
            parent_id = self.id
            child_id = self.default_child_category.id
        return reverse('article:category_detail', kwargs={
            'parent_id': parent_id,
            'child_id': child_id
        })


class Banner(BaseModel):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, limit_choices_to={'is_banner': True}, verbose_name="轮播图文章")
    image = models.ImageField(upload_to='banner/%Y/%m', max_length=100, verbose_name="轮播图照片")

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.article.title


class SiteSetting(models.Model):
    sitename = models.CharField(max_length=200, null=False, blank=False, default='', verbose_name="网站名称")
    site_description = models.TextField(max_length=1000, null=False, blank=False, default='', verbose_name="网站描述")
    site_seo_description = models.TextField(max_length=1000, null=False, blank=False, default='', verbose_name="网站SEO描述")
    site_keywords = models.TextField(max_length=1000, null=False, blank=False, default='', verbose_name="网站关键字")
    article_sub_length = models.IntegerField(default=250, verbose_name="文章摘要长度")
    beiancode = models.CharField(max_length=100, null=True, blank=True, default='', verbose_name="备案号")
    analyticscode = models.TextField(max_length=1000, null=False, blank=False, default='', verbose_name="网站统计代码")
    show_gongan_code = models.BooleanField(default=False, null=False, verbose_name="是否显示公安备案号")
    gongan_beiancode = models.CharField(max_length=100, null=True, blank=True, default='', verbose_name="公安备案号")

    class Meta:
        verbose_name = '网站配置'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sitename

    def clean(self):
        if SiteSetting.objects.exclude(id=self.id).count():
            raise ValidationError("只能有一个配置")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        from lbyledu.utils import cache
        cache.clear()

templates/article_index.html
{% extends "base.html" %}
{% load static %}
{% load article_tags %}

{% block head_title %}
{% query nav_category_list pk=current_parent_id as parent_category %}
{% for parent in parent_category %}{{ parent.name }}{% endfor %} - 豫灵镇中心学校
{% endblock head_title %}

{% block css %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock css %}

{% block sidebar %}
    <div class="col-sm-4 col-md-3 sidebar-offcanvas main-content-sidebar" id="sidebar">
        <ul class="sidebar-list-group">
            {% query nav_category_list pk=current_parent_id as parent_category %}
            {% query nav_category_list parent_category_id=current_parent_id as child_categorys %}
            <li><a href="{{ parent_category.get_absolute_url }}" class="sidebar-list-item top">{% for parent in parent_category %}{{ parent.name }}{% endfor %}</a></li>
            {% for node in child_categorys %}
            <li><a href="{{ node.get_absolute_url }}" class="sidebar-list-item{% if node.id == current_child_id %} active{% endif %}">{{ node.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock sidebar %}

{% block main %}
{% query nav_category_list pk=current_parent_id as parent_category %}
{% query nav_category_list pk=current_child_id as child_category %}
<div class="col-sm-8 col-md-9 main-content-body">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="panel-title-word">
                    <i class="fa fa-align-right"></i> {% for child in child_category %}{{ child.name }}{% endfor %}
                </span>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
                    <li class="breadcrumb-item"><a href="{{ parent_category.get_absolute_url }}">{% for parent in parent_category %}{{ parent.name }}{% endfor %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% for child in child_category %}{{ child.name }}{% endfor %}</li>
                </ol>
            </h3>
        </div>
        <div class="main-list-body panel-body">
            <ul class="list-group">
            {% for each_article in article_list %}
            <li class="list-group-item"><a href="{{ each_article.get_absolute_url }}">
                    <span class="list-group-item-title">{{ each_article.title }}</span>
                    <span class="list-group-item-date">{{ each_article.pub_date | date:"Y-m-d" }}</span>
                </a></li>
            {% empty %}
            <li class="list-group-item"><span class="list-group-item-title">暂无文章</span></li>
            {% endfor %}
            </ul>
            {% if is_paginated %}
            <nav aria-label="Page navigation example" class="main-pagination">
                <ul class="pagination pagination-sm justify-content-end">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">首页</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="">首页</a></li>
                    <li class="page-item disabled"><a class="page-link" href="">上一页</a></li>
                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
                    {% endif %}
                    {% for i in left %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                    <li class="page-item"><a class="page-link" href="?page={{  page_obj.number  }}">{{ page_obj.number }}</a></li>
                {% if right %}
                    {% for i in right %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    {% if right_has_more %}
                        <li class="page-item"><a class="page-link" href="javascript:void(0)">...</a></li>
                    {% endif %}
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="">下一页</a></li>
                    <li class="page-item disabled"><a class="page-link" href="">尾页</a></li>
                {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock main %}

templates/developing.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>页面开发中 - 灵宝市豫灵镇中心学校</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="../static/css/developing.css" rel="stylesheet">
</head>

<body>
    <div class="main-content">
        <div class="bg"></div>
        <div class="develop-card">
            <h1>页面正在开发中</h1>
            <h2>敬请期待</h2>
            <hr>
            <button><a href="/">返回主页</a></button>
        </div>
    </div>

    <!-- JavaScript -->
</body>

</html>

templates/footer.html
<footer class="main-footer">
    <p>灵宝市豫灵镇中心学校 © 版权所有 2007-{{ date | date:"Y" }}</p>
    <p>地址：河南省灵宝市豫灵镇亚武路 邮编：472533</p>
</footer>

templates/forget_password.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>找回密码 - 灵宝市豫灵镇中心学校</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/login.css'%}" rel="stylesheet">
</head>

<body>
    <div class="main-content">
        <div class="bg"></div>
        <div class="login-card">
            <div class="login-logo-card">
                <a href="{% url 'index' %}"><img src="{% static 'img/logo.png'%}" class="login-logo"></a>
            </div>
            <div class="login-form-card">
                <div class="login-form">
                    <h1><a href="{% url 'index' %}">豫灵镇中心学校</a></h1>
                    <h3>欢迎注册</h3>
                    <form action="{% url 'users:register' %}" method="POST">
                        <div class="form-row">
                            {% csrf_token %}
                            {{ form.none_field_errors }}
                            {{ form.email.label }}
                            {{ form.email }}
                            <div class="check-code">
                                {{ form.code.label }}
                                {{ form.code }}
                                <button type="submit" class="send-code-btn">发送验证码</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- JavaScript -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/header.html
{% load article_tags %}
{% load static %}
<header class="main-header">
    <div class="main-header-wordmark container-fluid">
        <div class="main-header-bar">
            <div class="main-head-top">
                <span class="return-old-version"><a href="http://lbyledu.cn/">旧站入口</a></span>
                {% if request.user.is_authenticated %}
                <div class="main-user">
                    <span>欢迎您，<a href="javascript:void(0)">{% if request.user.realname %}{{ request.user.realname }}{% else %}{{ request.user.username }}{% endif %} <i class="fa fa-caret-down"></i></a></span>
                    <div class="main-user-menu">
                        <a class="main-user-item" href="{{ request.user.get_absolute_url }}">个人中心</a>
                        <a class="main-user-item" href="javascript:void(0)">修改密码</a>
                        <a class="main-user-item" href="{% url 'users:logout' %}">退出登录</a>
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="main-search">
                <form action="">
                    <input type="text" class="main-search-input form-control" placeholder="搜索">
                    <button type="submit" class="main-search-submit btn"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="main-wordmark">
                <h1>灵宝市豫灵镇中心学校</h1>
                <h4>Lingbao Yuling Central School</h4>
            </div>
        </div>
    </div>
    <div class="main-header-navbar container-fluid">
        <nav class="main-header-bar navbar navbar-expand-sm">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-header-nav"
                    aria-controls="main-header-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="navbar-toggler-icon fa fa-bars"></i>
                </button>
            </div>
            <div id="main-header-nav" class="collapse navbar-collapse">
                <ul class="main-nav nav navbar-nav nav-justified">
                    <li class="nav-item"><a {% ifequal request.path "/" %}name="active" class="active"{% endifequal %} href="{% url 'index' %}">首页</a></li>
                    <li class="nav-item" data-toggle="tab" data-target="#main-nav-0"><a href="{% url 'article:developing' %}">学校概况</a></li>
                    {% query nav_category_list parent_category=None as root_categorys %}
                    {% for node in root_categorys %}
                        <li class="nav-item" data-toggle="tab" data-target="#main-nav-{{ forloop.counter }}"><a {% ifequal current_parent_id node.id %}name="active" class="active"{% endifequal %} href="{{ node.get_absolute_url }}">{{ node.name }}</a></li>
                    {% endfor %}
                    <li class="nav-item"{% if request.user.is_authenticated %} data-toggle="tab" data-target="#main-nav-99"{% endif %}><a {% if "/office/" in request.path %}name="active" class="active"{% endif %} href="{% url 'office:index' %}">网上办公</a></li>
                </ul>

                <ul class="main-nav-more">
                    <li class="fade" id="main-nav-0">
                        <div class="row">
                            <div class="col-sm-5 main-nav-item">
                                <ul class="main-nav-list">
                                    <li><a href="javascript:void(0)">学校概况</a></li>
                                    <li><a href="javascript:void(0)">领导介绍</a></li>
                                    <li><a href="javascript:void(0)">下属机构</a></li>
                                    <li><a href="javascript:void(0)">学校荣誉</a></li>
                                    <li><a href="javascript:void(0)">教育设施</a></li>
                                    <li><a href="javascript:void(0)">教研成果</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-3 main-nav-item">
                                <span class="main-nav-words">{{ SITE_NAME }}</span>
                            </div>
                            <div class="col-sm-4 main-nav-item">
                                <img class="main-nav-img" src="{% static 'img/2jiao.jpg' %}">
                            </div>
                        </div>
                    </li>
                    {% for node in root_categorys %}
                    {% query nav_category_list parent_category=node as child_categorys %}
                        {% if child_categorys %}
                        <li class="fade" id="main-nav-{{ forloop.counter }}">
                            <div class="row">
                                <div class="col-sm-5 main-nav-item">
                                    <ul class="main-nav-list">
                                    {% for child in child_categorys %}
                                        <li><a href="{{ child.get_absolute_url }}">{{ child.name }}</a></li>
                                    {% endfor %}
                                    </ul>
                                </div>
                                <div class="col-sm-3 main-nav-item">
                                    <span class="main-nav-words">{{ SITE_NAME }}</span>
                                </div>
                                <div class="col-sm-4 main-nav-item">
                                    <img class="main-nav-img" src="{% static 'img/2jiao.jpg' %}">
                                </div>
                            </div>
                        </li>
                        {% endif %}
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                    <li class="fade" id="main-nav-99">
                        <div class="row">
                            <div class="col-sm-5 main-nav-item">
                                <ul class="main-nav-list">
                                    <li><a href="{% url 'office:index' %}">办公首页</a></li>
                                    <li><a href="{% url 'office:document' %}">公文签收</a></li>
                                    <li><a href="{% url 'office:article' %}">文章管理</a></li>
                                    <li><a href="{% url 'office:user' %}">审核用户</a></li>
                                    <li><a href="{% url 'office:address_book' %}">通讯录</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-3 main-nav-item">
                                <span class="main-nav-words">{{ SITE_NAME }}</span>
                            </div>
                            <div class="col-sm-4 main-nav-item">
                                <img class="main-nav-img" src="{% static 'img/2jiao.jpg' %}">
                            </div>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
</header>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>登陆 - 灵宝市豫灵镇中心学校</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
</head>

<body>
    <div class="main-content">
        <div class="bg"></div>
        <div class="login-card">
            <div class="login-logo-card">
                <a href="{% url 'index' %}"><img src="{% static 'img/logo.png'%}" class="login-logo"></a>
            </div>
            <div class="login-form-card">
                <div class="login-form">
                    <h1><a href="{% url 'index' %}">豫灵镇中心学校</a></h1>
                    <h3>欢迎登陆</h3>
                    <form action="{% url 'users:login' %}" method="POST">
                    <div class="form-row">
                            {% csrf_token %}
                            {{ form.none_field_errors }}
                            {% for field in form %}
                            <div class="form-group col-12">
                                {{ field }}
                                {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors.as_text }}
                                </div>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <button type="submit" class="login-btn">登陆</button>
                        </div>
                    </form>
                    <div class="login-links">
                        <a href="{% url 'users:register' %}">注册账号</a>
                        <a href="javascript:void(0)">忘记密码</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JavaScript -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>注册 - 灵宝市豫灵镇中心学校</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/login.css'%}" rel="stylesheet">
</head>

<body>
    <div class="main-content">
        <div class="bg"></div>
        <div class="login-card">
            <div class="login-logo-card">
                <a href="{% url 'index' %}"><img src="{% static 'img/logo.png'%}" class="login-logo"></a>
            </div>
            <div class="login-form-card">
                <div class="login-form">
                    <h1><a href="{% url 'index' %}">豫灵镇中心学校</a></h1>
                    <h3>欢迎注册</h3>
                    <form action="{% url 'users:register' %}" method="POST">
                        <div class="form-row">
                            {% csrf_token %}
                            {{ form.none_field_errors }}
                            {% for field in form %}
                            <div class="form-group col-12">
                            {% if field.name == 'username' %}
                                {{ field }}
                                {% if field.errors or form.errors.invalid_username %}
                                <div class="invalid-feedback">
                                    {{ field.errors.as_text }}
                                    {{ form.errors.invalid_username }}
                                </div>
                                {% endif %}
                            {% elif field.name == 'email' %}
                            {{ field }}
                                {% if field.errors or form.errors.email_exists %}
                                <div class="invalid-feedback">
                                    {{ field.errors.as_text }}
                                    {{ form.errors.email_exists }}
                                </div>
                                {% endif %}
                            {% else %}
                                {{ field }}
                                {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors.as_text }}
                                </div>
                                {% endif %}
                            {% endif %}
                            </div>
                            {% endfor %}
                            <button type="submit" class="login-btn">注册</button>
                        </div>
                    </form>
                    <div class="login-links">
                        <a href="{% url 'users:login' %}">已有账号，点此登陆</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JavaScript -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/toolbar.html
<div id="toolbar">
    <div class="contactus">
        <a>
            联系我们
            <div class="contactus-card">
                <div class="contact-method">
                    <p>地址：河南省灵宝市豫灵镇亚武路</p>
                    <p>邮编：472533</p>
                    <p>电话：0398-2525678</p>
                </div>
            </div>
        </a>
    </div>
    <div class="returntop">
        <a><i class="fa fa-arrow-up"></i></a>
    </div>
</div>